### ISSUE TITLE
Pipes with parallel branches can return invalid tables

### ISSUE THREAD

**Issue by CameronBieganek** [JuliaML/TableTransforms.jl#223]
```julia
using TableTransforms

t = (a=1:4, b=5:8)

left = Select(:a) → Filter(row -> row.a < 4)
right = Select(:b) → Filter(row -> row.b < 7)
transform = left ⊔ right;
```

```julia
julia> transform(t)
(a = [1, 2, 3], b = [5, 6])
```

This should probably throw an error. But even if it did throw an error, it would illustrate a degree of freedom in the API design that allows the user to shoot themselves in the foot.

(The API design solution in my mind is to remove table queries from TableTransforms.jl and stick to ML and statistics transforms that preserve the number of rows of the input table.)

**Comment by CameronBieganek** [comment]
At least you get an error if you use a table type that actually enforces table-ness:

```julia
julia> df = DataFrame(a=1:4, b=5:8);

julia> transform(df)
ERROR: DimensionMismatch: column :a has length 3 and column :b has length 2
```

So the lack of an error for named tuples has more do to with the fuzziness of the `NamedTuple` table implementation in Tables.jl.

But the API design issue that I mentioned still stands.

**Comment by juliohm** [comment]
I think that targeting corner cases in a dynamic language that doesn't support compile time checks is a bad goal. We definitely want to educate users on how to use these transforms well and safely, but we don't want to remove features just to make things that are currently possible, impossible.

**Comment by ParadaCarleton** [comment]
> I think that targeting corner cases in a dynamic language that doesn't support compile time checks is a bad goal. We definitely want to educate users on how to use these transforms well and safely, but we don't want to remove features just to make things that are currently possible, impossible.

I think you might be misunderstanding the MWE above. This isn't a feature, it's a bug; there's no situation where you want to pass an invalid table as an input to TableTransforms.jl. This bug also isn't related to a lack of compile-time checks; checking size outputs with `filter` has to be done at runtime. 

TableTransforms.jl isn't throwing an error when it produces an impossible/invalid output right now, or when it's given an input that isn't a table (meaning the assumptions of TableTransforms.jl are being violated). If that gets passed through a pipeline, it's going to cause lots of problems downstream and a lot of confusion for users.

**Comment by CameronBieganek** [comment]
This particular MWE could be solved upstream by having the named-tuple-of-vectors materializer check that input column lengths are equal, which it currently does not:

```julia
julia> nt = (a=1:3, b=1:2)
(a = 1:3, b = 1:2)

julia> Tables.materializer(nt)(nt)
(a = 1:3, b = 1:2)
```

Then again, the correct fix for `Tables.materializer` is probably not within `Tables.materializer` but within the `Tables.columns` method for named tuples of vectors. There are two possible fixes for `Tables.columns`:

- Throw an error if the length of columns is different.
    - This is the solution that would fix the MWE without any changes to TableTransforms.jl)
- Return an iterator that pads short columns with `missing`.
    - This would not fix the MWE in this issue.

**Comment by CameronBieganek** [comment]
Let me clarify the underlying design issue. Running filters in parallel branches of a pipeline and then horizontally concatenating the results almost never makes sense. Can anyone think of a use case where this would actually make sense? Normally the only meaningful way to horizontally combine tables is with a `JOIN`.

**Comment by juliohm** [comment]
You're proposing that we should add an assertion to our parallel transform
to inhibt parallel branches that contain Filter?

Em ter., 31 de out. de 2023 16:18, Cameron Bieganek <
***@***.***> escreveu:

**Comment by CameronBieganek** [comment]
I am going to decline to make a specific proposal. :)

But if you did something like that, it would also have to handle `DropMissing` and `DropExtrema`.

**Comment by juliohm** [comment]
The only sensible thing we can do here is add a check after the parallel branches are completed to make sure that all tables have the same number of rows. Will add to our roadmap.

**Comment by CameronBieganek** [comment]
There are lots of ways to corrupt your data with parallel pipelines. Here are a couple more:

#### 1)

```julia
t = (a=[1, 2, 3], b=[3, 2, 1])

left = Select(:a)
right = Select(:b) → Sort(:b)
transform = left ⊔ right
```

```julia
julia> transform(t)
(a = [1, 2, 3], b = [1, 2, 3])
```

#### 2)

```julia
t = (a=1:4, b=1:4)

left = Select(:a) → Sample(3)
right = Select(:b) → Sample(3)
transform = left ⊔ right
```

```julia
julia> transform(t)
(a = [2, 1, 3], b = [3, 2, 1])
```

#### Discussion

It's virtually impossible to correctly use `Filter`, `DropMissing`, `DropExtrema`, `Sort`, and `Sample` in parallel branches of a pipeline, so it would make sense to at least emit a warning, if not an error, when those transforms appear in parallel branches.

The alternative, as I mentioned in the original post, is to leave table queries to Query.jl and DataFrames.jl. (Technically you can make the same mistakes with DataFrames because they have `hcat`, but you shouldn't normally be using `hcat`.)

**Comment by juliohm** [comment]
Both examples are valid. Maybe your mental model of parallel pipelines is not matching what we have here. Parallel pipelines simply combine the result of the branches with hcat, and that is clear from the docstring. There is no guarantee that rows of the original table will be processed together. If you ask to sort the column b and then hcat with column a, that is the expected result.

Regarding all transforms that change the number of rows, that is also expected. There are many other transforms that  change the number of rows: Potrace, Rasterize.

I don't think that Query.jl or DataFrames.jl address the same problem. The feature we have here is quite unique and powerful for the applications we are developing.

**Comment by CameronBieganek** [comment]
Whether you have a row-orientated table or a column-orientated table, individual data records are contained in rows. The examples above destroy the integrity of the data records.

#### 1)

The initial data records:

```julia
(1, 3)
(2, 2)
(3, 1)
```

The final data records:

```julia
(1, 1)
(2, 2)
(3, 3)
```

#### 2)

The initial data records:

```julia
(1, 1)
(2, 2)
(3, 3)
(4, 4)
````

The final data records:

```julia
(2, 3)
(1, 2)
(3, 1)
```

It's hard to imagine a scenario where this behavior is useful. But if you're ok with data corruption, then... 🤷‍♂️

**Comment by juliohm** [comment]
It is because for you this is invalid, but for many other people it may not be. It doesn't matter if the table is row-major or column-major, the transformation can do anything with the table and produce another table. It is the user who will build sensible pipelines for statistical analysis.

You are coming from the perspective that we should only allow transforms that make some sort of statistical sense. Again, think more broadly and understand that TableTransforms.jl is about transformations of tables, not just stats or ML.

**Comment by CameronBieganek** [comment]
> You are coming from the perspective that we should only allow transforms that make some sort of statistical sense.

No, this has nothing to do with statistics. It has everything to do with data contained in tables. The definition of a table is that data records are contained in rows. This is a broader concept than just statistical data. A table is fundamentally just a data structure for holding rows/records/tuples (whatever you want to call them). Each row is atomic, and each row contains the same number of elements. Mathematically a table is a *relation*---it's a subset of a cartesian product.

If that's not how you treat tables, then maybe you should name this package something else, like ArrayTransforms.jl.

**Comment by juliohm** [comment]
Tables are also a representation that associates column vectors to names.
No matter the definition, we can operate on these tables and produce new
tables. Invalidation as you describe can be a very delicate concept. Would
renaming the columns of the table be an invalidation of records? Would
replacing missing by 0 be an invalidation of records?

The issue here is still opened because we can throw a better error message
for the case where the parallel transform is returning columns with
different length. Other than that, the package name is completely fine.

Em ter., 31 de out. de 2023 18:45, Cameron Bieganek <
***@***.***> escreveu:

**Comment by CameronBieganek** [comment]
> Tables are also a representation that associates column vectors to names.

If tables were just a collection of named vectors, then the vectors could have different lengths. The requirement that tables have equal length columns follows from the definition of a table as a set of equal-sized rows.

> Would renaming the columns of the table be an invalidation of records? Would replacing missing by 0 be an invalidation of records?

Obviously some table transformations make sense. But splicing together half of one row with half of a different row from the same table is a big no-no.

Anyhow, that's all I have to say on this subject.

**Comment by juliohm** [comment]
| Obviously some table transformations make sense. But splicing together
half of one row with half of a different row from the same table is a big
no-no.

One may ask why, and in order to answer this question you will likely need
to rely on specific assumptions about the kinds of pipelines **you** have
in mind. For me it is completely valid and useful to splice together half
rows and columns together if the applications asks for it.

Thanks for the input.



Em ter., 31 de out. de 2023 19:11, Cameron Bieganek <
***@***.***> escreveu:

**Comment by ParadaCarleton** [comment]
> Both examples are valid. Maybe your mental model of parallel pipelines is not matching what we have here. Parallel pipelines simply combine the result of the branches with hcat, and that is clear from the docstring. There is no guarantee that rows of the original table will be processed together. If you ask to sort the column b and then hcat with column a, that is the expected result.

Right, so it's not a correctness bug in TableTransforms.jl, but it's behavior that could very easily lead to a correctness bug in user code. The problem here is that it's very easy to make a mistake or typo. When we have a suspicious-looking user input, our first question should be "What does the user want to do?"

But usually, when we filter a table, we either want to filter out columns or filter out rows. Usually, `Filter` commands aren't intended to mix-and-match variables, e.g. matching one country's oil reserves with a different country's growth rate.

But it's easy to absent-mindedly write a program that does this:
```julia
left = Select(:a) 
right = Select(:b) → Filter(:b)
transform = left ⊔ right
```

When what we really meant was this:
```julia
left = Select(:a) 
right = Select(:b)
transform = left ⊔ right → Filter(:b)
```
I think in the rare cases where a user does want to combine variables from different observations, it's better for them to write something more explicit, like `permute!(data.oil, sortperm(data.growth))`.

**Comment by ParadaCarleton** [comment]
@juliohm thank you so much for this! :smile:

**Comment by juliohm** [comment]
Thanks to @eliascarv who implemented the fix 👍🏽 

We are working on #221 next.
